name: haskell-bitcoin
version: 0.1.0.0
#synopsis:
#description:
homepage: https://github.com/githubuser/haskell-bitcoin#readme
license: BSD3
author: Author name here
maintainer: example@example.com
copyright: 2020 Author name here
category: Web
extra-source-files:
  - README.md

dependencies:
  - base >= 4.7 && < 5
  - lens
  - lens-aeson
  - bytestring
  - text
  - http-conduit

executables:
  haskell-bitcoin:
    source-dirs: src
    main: Main.hs
